export const vdcTokens = {
  colors: {
    ink: { value: "#0e0e10" },
    graphite: { value: "#17171a" },
    graphiteRaised: { value: "#202024" },
    graphiteHover: { value: "#29292e" },
    steel: { value: "#3a3a3e" },
    line: { value: "#343438" },
    warmWhite: { value: "#f2eee7" },
    text: { value: "#ebe7e1" },
    muted: { value: "#918d91" },
    subtle: { value: "#69666b" },
    vdcRed: { value: "#c4331e" },
    vdcRedBright: { value: "#e24a2d" },
    vdcRedDark: { value: "#8f2116" },
    success: { value: "#8fc6a2" },
    warning: { value: "#e4bf70" },
    danger: { value: "#e47972" },
    info: { value: "#86bce8" },
  },
  radii: {
    l1: { value: "8px" },
    l2: { value: "10px" },
    l3: { value: "12px" },
    l4: { value: "16px" },
    pill: { value: "999px" },
  },
  shadows: {
    xs: { value: "0 1px 2px rgba(0,0,0,.22)" },
    sm: { value: "0 8px 24px rgba(0,0,0,.20)" },
    md: { value: "0 18px 48px rgba(0,0,0,.28)" },
    lg: { value: "0 28px 80px rgba(0,0,0,.38)" },
    focus: { value: "0 0 0 3px rgba(196,51,30,.18)" },
  },
  durations: {
    fast: { value: "120ms" },
    normal: { value: "180ms" },
    slow: { value: "260ms" },
  },
  easings: {
    standard: { value: "cubic-bezier(.2,.8,.2,1)" },
    emphasized: { value: "cubic-bezier(.16,1,.3,1)" },
  },
  zIndex: {
    base: { value: 0 },
    sticky: { value: 20 },
    overlay: { value: 40 },
    modal: { value: 60 },
    toast: { value: 80 },
  },
} as const;

export const vdcSemanticTokens = {
  colors: {
    bg: { value: { base: "{colors.ink}" } },
    fg: { value: { base: "{colors.text}" } },
    "fg.muted": { value: { base: "{colors.muted}" } },
    "fg.subtle": { value: { base: "{colors.subtle}" } },
    "surface.bg": { value: { base: "{colors.graphite}" } },
    "surface.raised": { value: { base: "{colors.graphiteRaised}" } },
    "surface.hover": { value: { base: "{colors.graphiteHover}" } },
    "surface.border": { value: { base: "{colors.line}" } },
    "brand.solid": { value: { base: "{colors.vdcRed}" } },
    "brand.hover": { value: { base: "{colors.vdcRedBright}" } },
    "brand.subtle": { value: { base: "rgba(196,51,30,.10)" } },
    "brand.border": { value: { base: "rgba(196,51,30,.28)" } },
    "status.success": { value: { base: "{colors.success}" } },
    "status.warning": { value: { base: "{colors.warning}" } },
    "status.danger": { value: { base: "{colors.danger}" } },
    "status.info": { value: { base: "{colors.info}" } },
  },
} as const;
