export const vdcGlobalCss = {
  "html, body": {
    background: "bg",
    color: "fg",
  },
  body: {
    margin: "0",
    minHeight: "100dvh",
    fontFamily: "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    textRendering: "optimizeLegibility",
    WebkitFontSmoothing: "antialiased",
  },
  "*": { boxSizing: "border-box" },
  "a": { color: "inherit", textDecoration: "none" },
  "button, input, textarea, select": { font: "inherit" },

  ".page-stack": { display: "grid", gap: { base: "4", md: "5" } },
  ".page-heading": {
    display: "flex",
    flexDirection: { base: "column", md: "row" },
    alignItems: { base: "stretch", md: "end" },
    justifyContent: "space-between",
    gap: "4",
  },
  ".page-heading h1": {
    margin: "1.5 0 0",
    color: "fg",
    fontSize: { base: "30px", md: "38px" },
    fontWeight: "950",
    letterSpacing: "-0.045em",
    lineHeight: "1.05",
  },
  ".page-heading p": {
    maxWidth: "720px",
    margin: "2 0 0",
    color: "fg.muted",
    fontSize: "sm",
    lineHeight: "1.6",
  },
  ".eyebrow": {
    color: "brand.hover",
    fontSize: "9px",
    fontWeight: "900",
    letterSpacing: "0.13em",
    textTransform: "uppercase",
  },

  ".panel": {
    padding: { base: "3.5", md: "4" },
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: "l3",
    background: "surface.bg",
    boxShadow: "xs",
  },
  ".panel-wide": { gridColumn: { xl: "span 2" } },
  ".panel-grid, .dashboard-grid": {
    display: "grid",
    gridTemplateColumns: { base: "1fr", xl: "repeat(2,minmax(0,1fr))" },
    gap: "3",
  },
  ".panel-head": {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "3",
    marginBottom: "3",
    paddingBottom: "2.5",
    borderBottom: "1px solid",
    borderColor: "surface.border",
  },
  ".panel-head h2, .panel h2": {
    margin: "1 0 0",
    fontSize: "lg",
    fontWeight: "900",
  },
  ".panel p": { color: "fg.muted", lineHeight: "1.6" },

  ".stat-grid": {
    display: "grid",
    gridTemplateColumns: { base: "1fr", sm: "repeat(2,minmax(0,1fr))", xl: "repeat(4,minmax(0,1fr))" },
    gap: "3",
  },
  ".stat-card": {
    padding: "4",
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: "l3",
    background: "surface.bg",
  },
  ".stat-card span, .stat-card strong, .stat-card small": { display: "block" },
  ".stat-card span": { color: "fg.muted", fontSize: "xs" },
  ".stat-card strong": { margin: "1.5 0", color: "fg", fontSize: "28px", fontWeight: "950" },
  ".stat-card small": { color: "fg.subtle", fontSize: "10px" },

  ".primary-button, .ghost-button, .light-button, .mini-button": {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "2",
    minHeight: "9",
    paddingInline: "3",
    borderRadius: "l1",
    border: "1px solid",
    fontWeight: "850",
    cursor: "pointer",
    transitionDuration: "normal",
    transitionProperty: "background, border-color, color, transform",
  },
  ".primary-button": {
    borderColor: "brand.solid",
    background: "brand.solid",
    color: "warmWhite",
  },
  ".primary-button:hover": { background: "brand.hover", transform: "translateY(-1px)" },
  ".ghost-button, .mini-button": {
    borderColor: "surface.border",
    background: "surface.raised",
    color: "fg.muted",
  },
  ".ghost-button:hover, .mini-button:hover": {
    borderColor: "brand.border",
    background: "surface.hover",
    color: "fg",
  },
  ".light-button": { borderColor: "warmWhite", background: "warmWhite", color: "ink" },
  ".mini-button": { minHeight: "8", paddingInline: "2.5", fontSize: "xs" },
  ".text-link, .back-link": { color: "brand.hover", fontSize: "xs", fontWeight: "850" },
  ".text-link:hover, .back-link:hover": { textDecoration: "underline" },

  ".count-chip, .role-chip": {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "fit-content",
    padding: "1.5 2.5",
    borderRadius: "pill",
    background: "brand.subtle",
    color: "brand.hover",
    fontSize: "xs",
    fontWeight: "850",
  },

  ".form-stack": { display: "grid", gap: "3" },
  ".form-grid": { display: "grid", gridTemplateColumns: { base: "1fr", md: "repeat(2,minmax(0,1fr))" }, gap: "3" },
  ".form-stack label, .form-grid label": { display: "grid", gap: "1.5", color: "fg.muted", fontSize: "xs", fontWeight: "750" },
  ".form-stack input, .form-stack select, .form-stack textarea, .form-grid input, .form-grid select, .form-grid textarea": {
    width: "full",
    minHeight: "10",
    paddingInline: "3",
    paddingBlock: "2",
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: "l1",
    background: "surface.bg",
    color: "fg",
    outline: "none",
  },
  ".form-stack textarea, .form-grid textarea": { minHeight: "96px", resize: "vertical" },
  ".form-stack input:focus, .form-stack select:focus, .form-stack textarea:focus, .form-grid input:focus, .form-grid select:focus, .form-grid textarea:focus": {
    borderColor: "brand.solid",
    boxShadow: "focus",
  },

  ".management-grid": {
    display: "grid",
    gridTemplateColumns: { base: "1fr", xl: "minmax(0,1.65fr) minmax(280px,.75fr)" },
    gap: "3",
    alignItems: "start",
  },
  ".management-grid.single": { gridTemplateColumns: "1fr" },
  ".sticky-panel": { xl: { position: "sticky", top: "84px" } },

  ".data-list, .table-list": { display: "grid" },
  ".table-row": {
    display: "grid",
    gridTemplateColumns: { base: "1fr", md: "minmax(0,1fr) auto auto" },
    gap: "2",
    alignItems: "center",
    paddingBlock: "2.5",
    borderTop: "1px solid",
    borderColor: "surface.border",
  },
  ".table-row:first-child": { borderTop: "0" },

  ".empty-state": {
    padding: "5",
    color: "fg.muted",
    textAlign: "center",
    fontSize: "sm",
  },
  ".form-success, .form-error": {
    padding: "3",
    border: "1px solid",
    borderRadius: "l2",
    fontSize: "xs",
    fontWeight: "750",
  },
  ".form-success": {
    borderColor: "rgba(143,198,162,.22)",
    background: "rgba(143,198,162,.07)",
    color: "status.success",
  },
  ".form-error": {
    borderColor: "rgba(228,121,114,.24)",
    background: "rgba(228,121,114,.08)",
    color: "status.danger",
  },

  ".status-badge, .fee-status, .document-status, .survey-status": {
    display: "inline-flex",
    alignItems: "center",
    width: "fit-content",
    padding: "1.5 2.5",
    borderRadius: "pill",
    fontSize: "10px",
    fontWeight: "850",
  },
  ".status-active, .status-running, .status-completed, .status-done, .fee-paid, .document-active, .survey-status-active": {
    background: "rgba(143,198,162,.10)",
    color: "status.success",
  },
  ".status-planned, .status-review, .status-open, .status-in_progress": {
    background: "rgba(228,191,112,.10)",
    color: "status.warning",
  },
  ".status-passive, .fee-open, .document-review, .survey-status-draft": {
    background: "rgba(228,191,112,.10)",
    color: "status.warning",
  },
  ".status-inactive, .status-disabled, .status-cancelled, .status-blocked, .fee-cancelled, .document-expired": {
    background: "rgba(228,121,114,.10)",
    color: "status.danger",
  },
  ".status-archived, .status-draft": {
    background: "surface.hover",
    color: "fg.muted",
  },
  ".survey-status-closed": { background: "rgba(134,188,232,.10)", color: "status.info" },
  ".survey-status-archived": { background: "surface.hover", color: "fg.muted" },

  ".negative": { color: "status.danger !important" },
} as const;
