export const vdcMeetingGlobalCss = {
  ".meeting-control-page": {
    display: "grid",
    gap: { base: "4", md: "5" },
  },

  ".meeting-control-hero": {
    display: "flex",
    flexDirection: { base: "column", md: "row" },
    alignItems: { base: "stretch", md: "center" },
    justifyContent: "space-between",
    gap: "4",
    p: { base: "3.5", md: "4" },
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: "l4",
    background: "linear-gradient(135deg,rgba(196,51,30,.10),rgba(255,255,255,.01))",
    boxShadow: "sm",
  },
  ".meeting-control-title": {
    display: "flex",
    alignItems: "center",
    gap: "3",
    "& img": { width: "44px", height: "44px", flexShrink: "0" },
    "& h1": {
      margin: "1 0 0",
      fontSize: { base: "24px", md: "32px" },
      fontWeight: "950",
      letterSpacing: "-0.04em",
      lineHeight: "1.08",
    },
    "& p": { margin: "1.5 0 0", color: "fg.muted", fontSize: "xs" },
  },
  ".meeting-control-tools": {
    display: "flex",
    alignItems: "center",
    justifyContent: { base: "flex-start", md: "flex-end" },
    gap: "2",
    flexWrap: "wrap",
  },
  ".meeting-hero-more": { position: "relative" },
  ".meeting-hero-more>summary": { listStyle: "none" },
  ".meeting-hero-more>summary::-webkit-details-marker": { display: "none" },
  ".meeting-hero-more>div": {
    position: { md: "absolute" },
    right: "0",
    top: "calc(100% + 6px)",
    zIndex: "sticky",
    minWidth: "190px",
    p: "2",
    mt: { base: "2", md: "0" },
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: "l2",
    background: "surface.raised",
    boxShadow: "md",
  },

  ".meeting-workflow-bar": {
    display: "grid",
    gridTemplateColumns: { base: "1fr", md: "repeat(3,minmax(0,1fr))" },
    gap: "2",
    p: "1",
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: "l3",
    background: "surface.bg",
  },
  ".meeting-workflow-bar>a": {
    display: "grid",
    gridTemplateColumns: "32px minmax(0,1fr)",
    gap: "2",
    alignItems: "center",
    minHeight: "58px",
    p: "2.5",
    borderRadius: "l2",
    color: "fg.muted",
    "&>b": {
      display: "grid",
      placeItems: "center",
      width: "8",
      height: "8",
      borderRadius: "pill",
      background: "surface.hover",
      fontSize: "xs",
    },
    "& strong,& small": { display: "block" },
    "& strong": { color: "fg", fontSize: "xs", fontWeight: "900" },
    "& small": { mt: "0.5", color: "fg.muted", fontSize: "[9px]" },
  },
  ".meeting-workflow-bar>a.is-current": {
    background: "brand.subtle",
    boxShadow: "inset 0 0 0 1px rgba(196,51,30,.18)",
    "&>b": { background: "brand.solid", color: "warmWhite" },
  },
  ".meeting-workflow-bar>a.is-done": {
    "&>b": { background: "rgba(143,198,162,.12)", color: "status.success" },
  },

  ".meeting-control-stats": {
    display: "grid",
    gridTemplateColumns: { base: "repeat(2,minmax(0,1fr))", xl: "repeat(4,minmax(0,1fr))" },
    gap: "2",
  },
  ".meeting-control-stats>article": {
    p: "3",
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: "l2",
    background: "surface.bg",
    "& span,& strong,& small": { display: "block" },
    "& span": { color: "fg.muted", fontSize: "[10px]" },
    "& strong": { mt: "1", fontSize: "lg", fontWeight: "950" },
    "& small": { mt: "1", color: "fg.subtle", fontSize: "[9px]" },
  },
  ".meeting-control-stats>article.is-ready": {
    borderColor: "rgba(143,198,162,.20)",
    background: "rgba(143,198,162,.035)",
  },
  ".meeting-control-stats>article.needs-attention": {
    borderColor: "rgba(228,191,112,.22)",
    background: "rgba(228,191,112,.04)",
  },

  ".meeting-formalities-panel,.meeting-secretary-setup,.meeting-prep-agenda,.meeting-general-attachments,.meeting-carryover-panel,.meeting-completed-next": {
    display: "grid",
    gap: "3",
  },
  ".meeting-formalities-form,.meeting-officer-form,.meeting-agenda-add-form,.meeting-general-attachment-upload,.meeting-attachment-upload,.vote-exclusion-form,.meeting-live-inline-form,.meeting-close-form": {
    display: "grid",
    gap: "2.5",
  },
  ".meeting-formalities-form label,.meeting-officer-form label,.meeting-agenda-add-form label,.meeting-general-attachment-upload label,.meeting-attachment-upload label,.vote-exclusion-form label,.meeting-live-inline-form label,.meeting-close-form label": {
    display: "grid",
    gap: "1.5",
    color: "fg.muted",
    fontSize: "xs",
    fontWeight: "750",
  },
  ".meeting-formalities-form input,.meeting-formalities-form select,.meeting-formalities-form textarea,.meeting-officer-form input,.meeting-officer-form select,.meeting-officer-form textarea,.meeting-agenda-add-form input,.meeting-agenda-add-form select,.meeting-agenda-add-form textarea,.meeting-general-attachment-upload input,.meeting-attachment-upload input,.vote-exclusion-form input,.vote-exclusion-form select,.vote-exclusion-form textarea,.meeting-live-inline-form input,.meeting-live-inline-form select,.meeting-live-inline-form textarea,.meeting-close-form input,.meeting-close-form select,.meeting-close-form textarea": {
    width: "full",
    minHeight: "10",
    p: "2.5",
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: "l1",
    background: "surface.bg",
    color: "fg",
    outline: "none",
    _focus: { borderColor: "brand.solid", boxShadow: "focus" },
  },
  ".meeting-formal-readonly,.meeting-officer-readonly": {
    display: "flex",
    gap: "1.5",
    flexWrap: "wrap",
    "& span": {
      px: "2.5",
      py: "1.5",
      borderRadius: "pill",
      background: "surface.hover",
      color: "fg.muted",
      fontSize: "[10px]",
    },
  },
  ".formal-state": {
    display: "inline-flex",
    px: "2.5",
    py: "1.5",
    borderRadius: "pill",
    fontSize: "[10px]",
    fontWeight: "850",
  },
  ".formal-ok": { background: "rgba(143,198,162,.10)", color: "status.success" },
  ".formal-open": { background: "rgba(228,191,112,.10)", color: "status.warning" },

  ".meeting-session-shell": {
    display: "grid",
    gridTemplateColumns: { base: "1fr", xl: "[270px] minmax(0,1fr) [260px]" },
    gap: "3",
    alignItems: "start",
  },
  ".meeting-top-rail,.meeting-check-rail": {
    display: "grid",
    gap: "2",
    p: "3",
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: "l3",
    background: "surface.bg",
    xl: { position: "sticky", top: "82px", maxHeight: "calc(100dvh - 100px)", overflowY: "auto" },
  },
  ".meeting-top-rail-head,.meeting-check-head,.meeting-section-head": {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "2",
    "& h2,& h3": { fontSize: "sm", fontWeight: "900" },
  },
  ".meeting-top-list": {
    display: "grid",
    gap: "1.5",
  },
  ".meeting-top-link": {
    display: "grid",
    gridTemplateColumns: "30px minmax(0,1fr)",
    gap: "2",
    alignItems: "center",
    p: "2",
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: "l1",
    background: "surface.raised",
    color: "fg.muted",
    _hover: { borderColor: "brand.border", color: "fg" },
  },
  ".meeting-top-link.is-active,.meeting-top-link.top-active": {
    borderColor: "brand.border",
    background: "brand.subtle",
    color: "fg",
  },
  ".meeting-top-number": {
    display: "grid",
    placeItems: "center",
    width: "7",
    height: "7",
    borderRadius: "pill",
    background: "surface.hover",
    color: "brand.hover",
    fontSize: "[10px]",
    fontWeight: "900",
  },

  ".meeting-focus-panel": {
    minWidth: "0",
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: "l4",
    background: "surface.bg",
    boxShadow: "sm",
    overflow: "hidden",
  },
  ".meeting-focus-empty": { p: "7", textAlign: "center", color: "fg.muted" },
  ".meeting-focus-head": {
    display: "flex",
    flexDirection: { base: "column", sm: "row" },
    alignItems: { sm: "start" },
    justifyContent: "space-between",
    gap: "3",
    p: "4",
    borderBottom: "1px solid",
    borderColor: "surface.border",
    background: "surface.raised",
    "& h2": { mt: "1", fontSize: { base: "xl", md: "2xl" }, fontWeight: "950", lineHeight: "1.15" },
  },
  ".meeting-focus-status": { display: "flex", gap: "1.5", flexWrap: "wrap" },
  ".agenda-status": {
    display: "inline-flex",
    px: "2.5",
    py: "1.5",
    borderRadius: "pill",
    background: "surface.hover",
    color: "fg.muted",
    fontSize: "[10px]",
    fontWeight: "850",
  },
  ".agenda-active": { background: "brand.subtle", color: "brand.hover" },
  ".agenda-done": { background: "rgba(143,198,162,.10)", color: "status.success" },
  ".agenda-deferred": { background: "rgba(228,191,112,.10)", color: "status.warning" },
  ".meeting-focus-content": { display: "grid", gap: "3", p: "4" },
  ".meeting-read-note,.meeting-formal-note": {
    p: "3",
    borderLeft: "3px solid",
    borderColor: "brand.solid",
    borderRadius: "0 l1 l1 0",
    background: "brand.subtle",
    color: "fg.muted",
    fontSize: "sm",
    lineHeight: "1.6",
  },
  ".meeting-top-more,.meeting-top-danger-more,.meeting-live-options,.meeting-agenda-planner,.meeting-start-panel,.meeting-close-drawer,.meeting-prep-more,.meeting-resolution-summary,.meeting-no-resolution": {
    overflow: "hidden",
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: "l2",
    background: "surface.raised",
  },
  ".meeting-top-more>summary,.meeting-top-danger-more>summary,.meeting-live-options>summary,.meeting-agenda-planner>summary,.meeting-start-panel>summary,.meeting-close-drawer>summary,.meeting-prep-more>summary": {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "2",
    p: "2.5",
    cursor: "pointer",
    listStyle: "none",
    color: "fg.muted",
    fontSize: "xs",
    fontWeight: "850",
  },
  ".meeting-top-more>summary::-webkit-details-marker,.meeting-top-danger-more>summary::-webkit-details-marker,.meeting-live-options>summary::-webkit-details-marker,.meeting-agenda-planner>summary::-webkit-details-marker,.meeting-start-panel>summary::-webkit-details-marker,.meeting-close-drawer>summary::-webkit-details-marker,.meeting-prep-more>summary::-webkit-details-marker": {
    display: "none",
  },
  ".meeting-top-more[open]>summary,.meeting-top-danger-more[open]>summary,.meeting-live-options[open]>summary,.meeting-agenda-planner[open]>summary,.meeting-start-panel[open]>summary,.meeting-close-drawer[open]>summary,.meeting-prep-more[open]>summary": {
    borderBottom: "1px solid",
    borderColor: "surface.border",
    color: "fg",
  },
  ".meeting-top-more-body,.meeting-live-options-body,.meeting-close-body,.meeting-prep-more-body": { p: "3" },

  ".meeting-top-formal-block,.meeting-resolution-summary,.meeting-no-resolution": { p: "3" },
  ".meeting-top-formal-form": { display: "grid", gap: "2.5", mt: "2" },
  ".vote-exclusion-list,.meeting-attachment-list,.meeting-live-correction-list": { display: "grid", gap: "1.5", mt: "2" },

  ".meeting-attachment-list>div,.vote-exclusion-list>div,.meeting-live-correction-list>div": {
    display: "flex",
    flexDirection: { base: "column", sm: "row" },
    justifyContent: "space-between",
    alignItems: { sm: "center" },
    gap: "2",
    p: "2.5",
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: "l1",
    background: "surface.bg",
  },

  ".meeting-action-bar": {
    position: { xl: "sticky" },
    bottom: { xl: "12px" },
    zIndex: "sticky",
    display: "grid",
    gap: "2",
    p: "2.5",
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: "l3",
    background: "rgba(23,23,26,.94)",
    backdropFilter: "blur(16px)",
    boxShadow: "md",
  },
  ".meeting-action-center": {
    display: "flex",
    justifyContent: "center",
    gap: "2",
    flexWrap: "wrap",
  },
  ".meeting-action": {
    minHeight: "9",
  },
  ".meeting-action.primary": {
    borderColor: "brand.solid",
    background: "brand.solid",
    color: "warmWhite",
  },
  ".meeting-action.secondary": {
    borderColor: "surface.border",
    background: "surface.raised",
    color: "fg",
  },

  ".meeting-check-metrics": {
    display: "grid",
    gridTemplateColumns: { base: "repeat(2,minmax(0,1fr))", xl: "1fr" },
    gap: "1.5",
  },
  ".meeting-check-metrics>div": {
    p: "2",
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: "l1",
    background: "surface.raised",
    "& span,& strong": { display: "block" },
    "& span": { color: "fg.muted", fontSize: "[9px]" },
    "& strong": { mt: "1", fontSize: "xs" },
  },
  ".meeting-check-warnings": { display: "grid", gap: "1.5" },
  ".meeting-check-warnings>div": {
    p: "2",
    border: "1px solid",
    borderColor: "rgba(228,191,112,.22)",
    borderRadius: "l1",
    background: "rgba(228,191,112,.05)",
    color: "status.warning",
    fontSize: "[10px]",
  },

  ".meeting-close-grid": {
    display: "grid",
    gridTemplateColumns: { base: "1fr", md: "repeat(2,minmax(0,1fr))" },
    gap: "2.5",
  },
  ".meeting-close-help,.meeting-close-summary": {
    p: "2.5",
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: "l1",
    background: "surface.bg",
    color: "fg.muted",
    fontSize: "xs",
    lineHeight: "1.5",
  },
  ".meeting-next-create": {
    display: "flex",
    alignItems: "start",
    gap: "2",
    p: "2.5",
    border: "1px solid",
    borderColor: "brand.border",
    borderRadius: "l1",
    background: "brand.subtle",
  },
  ".meeting-close-submit": { width: { base: "full", sm: "auto" } },

  ".meeting-carryover-list": { display: "grid", gap: "2" },
  ".meeting-carryover-list>article": {
    display: "grid",
    gap: "2",
    p: "3",
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: "l2",
    background: "surface.raised",
  },

  ".meeting-management-grid": {
    display: "grid",
    gridTemplateColumns: { base: "1fr", xl: "repeat(2,minmax(0,1fr))" },
    gap: "3",
    alignItems: "start",
  },
  ".attendee-list,.meeting-guest-list": { display: "grid" },
  ".attendee-row": {
    display: "grid",
    gridTemplateColumns: { base: "40px minmax(0,1fr)", sm: "40px minmax(0,1fr) auto" },
    gap: "2.5",
    alignItems: "center",
    py: "2.5",
    borderTop: "1px solid",
    borderColor: "surface.border",
  },
  ".attendee-row:first-child": { borderTop: "0" },
  ".attendee-remove-form": { gridColumn: { base: "2", sm: "auto" } },
  ".attendee-add-form,.meeting-guest-form": { display: "grid", gap: "2.5", mt: "3" },

  ".meeting-start-panel": { borderColor: "brand.border" },
  ".meeting-start-head": { p: "3", borderBottom: "1px solid", borderColor: "surface.border" },
  ".meeting-start-blocked": {
    p: "3",
    border: "1px solid",
    borderColor: "rgba(228,191,112,.22)",
    borderRadius: "l2",
    background: "rgba(228,191,112,.05)",
    color: "status.warning",
  },
  ".meeting-start-form": { display: "grid", gap: "3", p: "3" },
  ".meeting-start-step": {
    display: "grid",
    gridTemplateColumns: { base: "1fr", sm: "34px minmax(0,1fr)" },
    gap: "2.5",
    p: "3",
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: "l2",
    background: "surface.bg",
  },
  ".meeting-start-step-number": {
    display: "grid",
    placeItems: "center",
    width: "8.5",
    height: "8.5",
    borderRadius: "pill",
    background: "brand.subtle",
    color: "brand.hover",
    fontSize: "xs",
    fontWeight: "950",
  },
  ".meeting-start-step-content": { minWidth: "0" },
  ".meeting-start-step-head": {
    display: "flex",
    justifyContent: "space-between",
    gap: "2",
    "& strong": { fontSize: "xs", fontWeight: "900" },
  },
  ".meeting-start-attendees": { display: "grid", gap: "1.5", mt: "2" },
  ".meeting-start-person": {
    display: "flex",
    flexDirection: { base: "column", sm: "row" },
    justifyContent: "space-between",
    gap: "2",
    p: "2",
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: "l1",
    background: "surface.raised",
  },
  ".meeting-attendance-choice,.meeting-quorum-choice": {
    display: "flex",
    gap: "1.5",
    flexWrap: "wrap",
  },
  ".meeting-start-submit": { display: "flex", justifyContent: "flex-end" },

  ".meeting-agenda-plan-list": { display: "grid", gap: "1.5", p: "3" },
  ".meeting-agenda-plan-list>article": {
    display: "grid",
    gridTemplateColumns: { base: "32px minmax(0,1fr)", md: "32px 34px minmax(0,1fr) auto" },
    gap: "2",
    alignItems: "center",
    p: "2.5",
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: "l1",
    background: "surface.bg",
  },
  ".agenda-drag-handle": {
    display: "grid",
    placeItems: "center",
    color: "fg.subtle",
    cursor: "grab",
  },
  ".agenda-plan-number": {
    display: "grid",
    placeItems: "center",
    width: "7.5",
    height: "7.5",
    borderRadius: "pill",
    background: "surface.hover",
    color: "brand.hover",
    fontSize: "[10px]",
    fontWeight: "900",
  },
  ".agenda-plan-main": {
    minWidth: "0",
    "& strong": { display: "block", fontSize: "xs" },
    "& span": { display: "block", mt: "1", color: "fg.muted", fontSize: "[10px]" },
  },
  ".agenda-late-chip": {
    display: "inline-flex",
    width: "fit-content",
    mt: "1",
    px: "2",
    py: "1",
    borderRadius: "pill",
    background: "rgba(228,191,112,.10)",
    color: "status.warning",
    fontSize: "[9px]",
  },
  ".agenda-plan-actions": {
    display: "flex",
    gap: "1.5",
    flexWrap: "wrap",
    gridColumn: { base: "2", md: "auto" },
  },
  ".agenda-plan-editor": {
    gridColumn: { base: "1 / -1" },
    display: "grid",
    gap: "2",
    pt: "2",
    borderTop: "1px solid",
    borderColor: "surface.border",
  },
  ".agenda-order-status": { color: "fg.muted", fontSize: "[10px]" },

  ".meeting-modal-backdrop": {
    position: "fixed",
    inset: "0",
    zIndex: "overlay",
    display: "grid",
    placeItems: { base: "end stretch", md: "center" },
    p: { base: "0", md: "4" },
    background: "rgba(0,0,0,.72)",
    backdropFilter: "blur(4px)",
  },
  ".meeting-resolution-modal": {
    position: "relative",
    width: "full",
    maxWidth: "700px",
    maxHeight: { base: "92dvh", md: "86dvh" },
    overflowY: "auto",
    p: "4",
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: { base: "l4 l4 0 0", md: "l4" },
    background: "surface.raised",
    boxShadow: "lg",
  },
  ".meeting-modal-close": {
    position: "absolute",
    top: "3",
    right: "3",
  },
  ".meeting-resolution-modal-form": { display: "grid", gap: "3", mt: "3" },
  ".meeting-vote-box,.meeting-vote-context": {
    p: "3",
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: "l2",
    background: "surface.bg",
  },
  ".vote-input-grid": {
    display: "grid",
    gridTemplateColumns: { base: "1fr", sm: "repeat(3,minmax(0,1fr))" },
    gap: "2",
  },
  ".meeting-resolution-task": {
    p: "3",
    border: "1px solid",
    borderColor: "brand.border",
    borderRadius: "l2",
    background: "brand.subtle",
  },

  ".meeting-autosave-notes": { display: "grid", gap: "2" },
  ".meeting-note-templates": { display: "flex", gap: "1.5", flexWrap: "wrap" },

  ".muted-copy,.compact-empty": { color: "fg.muted", fontSize: "xs", lineHeight: "1.5" },
} as const;
