export const vdcAdminGlobalCss = {
  ".admin-heading": {
    display:"flex",flexDirection:{base:"column",md:"row"},alignItems:{md:"end"},justifyContent:"space-between",gap:"3",
  },
  ".admin-lock-chip,.admin-warning-chip,.permission-chip": {
    display:"inline-flex",width:"fit-content",alignItems:"center",gap:"1.5",px:"2.5",py:"1.5",
    border:"1px solid",borderColor:"surface.border",borderRadius:"pill",background:"surface.raised",
    color:"fg.muted",fontSize:"[10px]",fontWeight:"850",
  },
  ".admin-warning-chip":{borderColor:"rgba(228,191,112,.22)",background:"rgba(228,191,112,.06)",color:"status.warning"},
  ".permission-admin":{borderColor:"brand.border",background:"brand.subtle",color:"brand.hover"},

  ".admin-launch-grid,.admin-hidden-grid": {
    display:"grid",gridTemplateColumns:{base:"1fr",sm:"repeat(2,minmax(0,1fr))",xl:"repeat(3,minmax(0,1fr))"},gap:"3",
  },
  ".admin-launch-card": {
    display:"grid",gridTemplateColumns:"40px minmax(0,1fr)",gap:"3",p:"3.5",
    border:"1px solid",borderColor:"surface.border",borderRadius:"l3",background:"surface.bg",
    transitionDuration:"normal",transitionProperty:"background, border-color, transform",
    _hover:{background:"surface.raised",borderColor:"brand.border",transform:"translateY(-1px)"},
    "& strong":{display:"block",fontSize:"sm",fontWeight:"900"},"& span":{display:"block",mt:"1",color:"fg.muted",fontSize:"[10px]",lineHeight:"1.45"},
  },
  ".admin-launch-icon":{display:"grid",placeItems:"center",width:"10",height:"10",borderRadius:"l2",background:"brand.subtle",color:"brand.hover"},
  ".admin-info-panel":{borderColor:"brand.border !important"},

  ".admin-user-list":{display:"grid",gap:"2"},
  ".admin-user-card":{display:"grid",gap:"3",p:"3.5",border:"1px solid",borderColor:"surface.border",borderRadius:"l3",background:"surface.bg"},
  ".admin-user-head":{display:"grid",gridTemplateColumns:{base:"40px minmax(0,1fr)",md:"40px minmax(0,1fr) auto"},gap:"2.5",alignItems:"center"},
  ".admin-user-state":{gridColumn:{base:"2",md:"auto"}},
  ".admin-user-meta":{display:"flex",gap:"1.5",flexWrap:"wrap","& span":{px:"2",py:"1",borderRadius:"pill",background:"surface.hover",color:"fg.muted",fontSize:"[9px]"}},
  ".admin-role-form":{display:"grid",gap:"3",pt:"3",borderTop:"1px solid",borderColor:"surface.border"},
  ".admin-user-actions":{display:"flex",gap:"2",flexWrap:"wrap"},

  ".role-matrix":{display:"grid",overflowX:"auto"},
  ".role-matrix-row":{display:"grid",gridTemplateColumns:"minmax(170px,1fr) minmax(360px,2fr)",gap:"3",minWidth:"620px",p:"2.5",borderTop:"1px solid",borderColor:"surface.border"},
  ".role-matrix-row:first-child":{borderTop:"0"},
  ".role-matrix-title":{fontSize:"xs",fontWeight:"900"},
  ".role-matrix-permissions":{display:"flex",gap:"1.5",flexWrap:"wrap"},
  ".admin-member-link-grid":{display:"grid",gridTemplateColumns:{base:"1fr",md:"repeat(2,minmax(0,1fr))"},gap:"2"},

  ".integration-control-panel":{borderColor:"brand.border !important"},
  ".integration-grid":{display:"grid",gridTemplateColumns:{base:"1fr",xl:"repeat(2,minmax(0,1fr))"},gap:"3"},
  ".integration-card":{display:"grid",gap:"3",p:"3.5",border:"1px solid",borderColor:"surface.border",borderRadius:"l3",background:"surface.bg"},
  ".integration-card-head":{display:"grid",gridTemplateColumns:{base:"42px minmax(0,1fr)",md:"42px minmax(0,1fr) auto"},gap:"3",alignItems:"center","& > :last-child":{gridColumn:{base:"2",md:"auto"},justifySelf:{base:"start",md:"end"}}},
  ".integration-logo":{display:"grid",placeItems:"center",width:"10.5",height:"10.5",border:"1px solid",borderColor:"brand.border",borderRadius:"l2",background:"brand.subtle",color:"brand.hover",fontSize:"[10px]",fontWeight:"950"},
  ".integration-status":{display:"inline-flex",px:"2.5",py:"1.5",borderRadius:"pill",fontSize:"[10px]",fontWeight:"850"},
  ".integration-connected":{background:"rgba(143,198,162,.10)",color:"status.success"},
  ".integration-disabled":{background:"surface.hover",color:"fg.muted"},
  ".integration-error":{p:"2.5",border:"1px solid",borderColor:"rgba(228,121,114,.22)",borderRadius:"l1",background:"rgba(228,121,114,.05)",color:"status.danger",fontSize:"xs"},
  ".integration-metrics":{display:"grid",gridTemplateColumns:{base:"repeat(2,minmax(0,1fr))",sm:"repeat(4,minmax(0,1fr))"},gap:"2","&>div":{minWidth:"0",p:"2.5",border:"1px solid",borderColor:"surface.border",borderRadius:"l1",background:"surface.raised"}},
  ".integration-meta":{display:"grid",gap:"1.5",pt:"2.5",borderTop:"1px solid",borderColor:"surface.border",color:"fg.muted",fontSize:"[10px]"},
  ".integration-card-actions":{display:"flex",gap:"1.5",flexWrap:"wrap"},
  ".sync-run-list":{display:"grid"},
  ".sync-run-row":{display:"grid",gridTemplateColumns:"10px minmax(0,1fr) auto",gap:"2",alignItems:"center",py:"2",borderTop:"1px solid",borderColor:"surface.border"},
  ".sync-run-dot":{width:"2",height:"2",borderRadius:"pill",background:"fg.subtle"},
  ".sync-run-success":{background:"status.success"},
  ".sync-run-partial":{background:"status.warning"},
  ".sync-run-error":{background:"status.danger"},

  ".architecture-flow":{display:"grid",gridTemplateColumns:{base:"1fr",md:"auto 40px auto 40px auto"},gap:"2",alignItems:"center",justifyContent:"center"},
  ".architecture-core":{p:"3",border:"1px solid",borderColor:"brand.border",borderRadius:"l2",background:"brand.subtle",textAlign:"center"},
  ".api-note":{p:"3",border:"1px solid",borderColor:"surface.border",borderRadius:"l2",background:"surface.raised",color:"fg.muted",fontSize:"xs",lineHeight:"1.5"},
  ".api-endpoint-list,.system-detail-list,.env-status-list,.system-integration-table,.audit-list,.export-link-list,.trash-list":{display:"grid"},
  ".system-detail-list>div,.env-status-list>div,.system-integration-table>div,.api-endpoint-list>div":{display:"grid",gridTemplateColumns:{base:"1fr",sm:"minmax(0,1fr) auto"},gap:"2",py:"2.5",borderTop:"1px solid",borderColor:"surface.border","&:first-child":{borderTop:"0"}},
  ".system-detail-wide":{gridColumn:"1/-1"},
  ".system-dot":{display:"inline-block",width:"2",height:"2",borderRadius:"pill",background:"status.success"},
  ".form-hint":{color:"fg.muted",fontSize:"[10px]",lineHeight:"1.45"},

  ".audit-row":{display:"grid",gridTemplateColumns:{base:"12px minmax(0,1fr)",md:"12px minmax(0,1fr) auto"},gap:"2.5",alignItems:"start",py:"2.5",borderTop:"1px solid",borderColor:"surface.border","& time":{gridColumn:{base:"2",md:"auto"},color:"fg.subtle",fontSize:"[10px]",whiteSpace:{md:"nowrap"}}},
  ".audit-row:first-child":{borderTop:"0"},
  ".audit-marker":{width:"2.5",height:"2.5",mt:"1",borderRadius:"pill",background:"brand.solid"},
  ".audit-main":{minWidth:"0"},
  ".audit-title":{display:"flex",gap:"2",flexWrap:"wrap","& strong":{fontSize:"xs",fontWeight:"900"},"& span":{color:"fg.muted",fontSize:"[10px]"}},

  ".quality-check-grid,.quality-detail-grid":{display:"grid",gridTemplateColumns:{base:"1fr",md:"repeat(2,minmax(0,1fr))",xl:"repeat(3,minmax(0,1fr))"},gap:"2"},
  ".quality-check-grid>article,.quality-detail-grid>article":{p:"3",border:"1px solid",borderColor:"surface.border",borderRadius:"l2",background:"surface.raised"},
  ".export-link":{display:"flex",justifyContent:"space-between",gap:"2",p:"2.5",border:"1px solid",borderColor:"surface.border",borderRadius:"l1",background:"surface.raised",_hover:{borderColor:"brand.border"}},
  ".panel-accent":{borderColor:"brand.border !important",background:"brand.subtle !important"},
  ".backup-note":{p:"3",border:"1px solid",borderColor:"surface.border",borderRadius:"l2",background:"surface.raised",color:"fg.muted",fontSize:"xs",lineHeight:"1.5"},

  ".trash-page":{display:"grid",gap:{base:"4",md:"5"}},
  ".trash-warning-panel":{borderColor:"rgba(228,121,114,.22) !important",background:"rgba(228,121,114,.035) !important"},
  ".trash-row":{display:"grid",gridTemplateColumns:{base:"1fr",md:"minmax(0,1fr) auto"},gap:"3",alignItems:"center",py:"2.5",borderTop:"1px solid",borderColor:"surface.border"},
  ".trash-row:first-child":{borderTop:"0"},
  ".trash-row-main":{minWidth:"0","& strong,& span":{display:"block"},"& strong":{fontSize:"xs"},"& span":{mt:"1",color:"fg.muted",fontSize:"[10px]"}},
  ".trash-row-actions":{display:"flex",gap:"1.5",flexWrap:"wrap"},
  ".danger-button":{borderColor:"rgba(228,121,114,.24) !important",background:"rgba(228,121,114,.08) !important",color:"status.danger !important"},
} as const;
