export const vdcContentGlobalCss = {
  ".guide-heading":{display:"flex",flexDirection:{base:"column",md:"row"},justifyContent:"space-between",alignItems:{md:"end"},gap:"3"},
  ".guide-role-card,.guide-access-note,.guide-auto-sync,.survey-anonymous-note":{p:"3",border:"1px solid",borderColor:"brand.border",borderRadius:"l2",background:"brand.subtle",color:"fg.muted",fontSize:"xs",lineHeight:"1.5"},
  ".guide-intro,.guide-install-grid,.guide-grid":{display:"grid",gridTemplateColumns:{base:"1fr",lg:"repeat(2,minmax(0,1fr))"},gap:"3"},
  ".guide-flow,.guide-workflow-steps,.guide-survey-workflow":{display:"grid",gap:"2"},
  ".guide-flow>div,.guide-workflow-steps>div,.guide-card":{p:"3",border:"1px solid",borderColor:"surface.border",borderRadius:"l2",background:"surface.raised"},
  ".guide-card-head":{display:"flex",justifyContent:"space-between",gap:"3",alignItems:"start","& h2,& h3":{fontSize:"sm",fontWeight:"900"}},
  ".guide-capabilities":{display:"flex",gap:"1.5",flexWrap:"wrap","& span":{px:"2",py:"1",borderRadius:"pill",background:"surface.hover",color:"fg.muted",fontSize:"[9px]"}},
  ".guide-install-app":{display:"grid",gap:"2"},
  ".guide-footer-copy":{color:"fg.subtle",fontSize:"[10px]",textAlign:"center"},

  ".document-detail-page":{display:"grid",gap:{base:"4",md:"5"}},
  ".document-detail-status":{display:"flex",alignItems:"center",gap:"1.5",flexWrap:"wrap"},
  ".document-system-chip":{display:"inline-flex",px:"2.5",py:"1.5",borderRadius:"pill",background:"brand.subtle",color:"brand.hover",fontSize:"[10px]",fontWeight:"850"},
  ".document-managed-protocol":{display:"flex",flexDirection:{base:"column",md:"row"},justifyContent:"space-between",alignItems:{md:"center"},gap:"3",p:"3.5",border:"1px solid",borderColor:"brand.border",borderRadius:"l3",background:"brand.subtle","& strong,& span,& small":{display:"block"},"& strong":{mt:"1",fontSize:"xs"},"& small":{mt:"1",color:"fg.muted",fontSize:"[10px]"}},
  ".document-detail-summary":{display:"grid",gridTemplateColumns:{base:"1fr",xl:"minmax(0,1.5fr) minmax(270px,.7fr)"},gap:"3"},
  ".document-current-card":{display:"grid",gap:"3"},
  ".document-current-file,.document-link-card":{p:"3",border:"1px solid",borderColor:"surface.border",borderRadius:"l2",background:"surface.raised"},
  ".document-current-actions":{display:"flex",gap:"1.5",flexWrap:"wrap"},
  ".document-no-file":{p:"4",color:"fg.muted",textAlign:"center"},
  ".document-integrity-row":{display:"flex",gap:"2",flexWrap:"wrap",color:"fg.muted",fontSize:"[10px]"},
  ".document-link-detail-list":{display:"grid",gap:"1.5",mt:"2","& span":{color:"fg.muted",fontSize:"[10px]"}},
  ".document-version-locked":{p:"2.5",border:"1px solid",borderColor:"rgba(228,191,112,.22)",borderRadius:"l1",background:"rgba(228,191,112,.05)",color:"status.warning",fontSize:"xs"},
  ".document-upload-box":{display:"grid",gap:"2",p:"3",border:"1px dashed",borderColor:"brand.border",borderRadius:"l2",background:"brand.subtle"},
  ".document-source-divider":{display:"flex",alignItems:"center",gap:"2",color:"fg.subtle",fontSize:"[10px]","&::before,&::after":{content:'""',flex:"1",height:"1px",background:"surface.border"}},
  ".document-danger-section":{borderColor:"rgba(228,121,114,.22) !important",background:"rgba(228,121,114,.035) !important"},
  ".document-version-history,.document-version-list":{display:"grid",gap:"2"},
  ".document-version-row":{display:"grid",gridTemplateColumns:{base:"36px minmax(0,1fr)",md:"36px minmax(0,1fr) auto"},gap:"2.5",alignItems:"center",p:"2.5",border:"1px solid",borderColor:"surface.border",borderRadius:"l2",background:"surface.raised"},
  ".document-version-row.is-current":{borderColor:"brand.border",background:"brand.subtle"},
  ".document-version-number":{display:"grid",placeItems:"center",width:"8",height:"8",borderRadius:"pill",background:"surface.hover",color:"brand.hover",fontSize:"[10px]",fontWeight:"900"},
  ".document-version-main":{minWidth:"0","& strong,& span":{display:"block"},"& strong":{fontSize:"xs"},"& span":{mt:"1",color:"fg.muted",fontSize:"[10px]"}},
  ".document-version-meta":{gridColumn:{base:"2",md:"auto"},color:"fg.muted",fontSize:"[10px]"},

  ".notification-page-count":{display:"flex",gap:"1.5",flexWrap:"wrap"},
  ".notification-page-list":{display:"grid",gap:"2"},
  ".notification-page-row":{display:"grid",gridTemplateColumns:"10px minmax(0,1fr) auto",gap:"2.5",alignItems:"start",p:"3",border:"1px solid",borderColor:"surface.border",borderRadius:"l2",background:"surface.bg"},
  ".notification-page-dot":{width:"2.5",height:"2.5",mt:"1",borderRadius:"pill",background:"status.info"},
  ".notification-critical .notification-page-dot":{background:"status.danger"},
  ".notification-warning .notification-page-dot":{background:"status.warning"},
  ".notification-info .notification-page-dot":{background:"status.info"},
  ".notification-page-main":{minWidth:"0","& strong,& span":{display:"block"},"& strong":{fontSize:"xs",fontWeight:"900"},"& span":{mt:"1",color:"fg.muted",fontSize:"[10px]",lineHeight:"1.45"}},
  ".notification-page-actions":{display:"flex",gap:"1.5",flexWrap:"wrap"},

  ".search-page":{display:"grid",gap:{base:"4",md:"5"}},
  ".global-search-panel":{borderColor:"brand.border !important"},
  ".global-search-form":{display:"grid",gridTemplateColumns:{base:"1fr",md:"minmax(0,1fr) auto"},gap:"2.5","& input":{width:"full",minHeight:"10",px:"3",border:"1px solid",borderColor:"surface.border",borderRadius:"l1",background:"surface.bg",color:"fg",outline:"none",_focus:{borderColor:"brand.solid",boxShadow:"focus"}}},
  ".search-summary":{display:"flex",gap:"1.5",flexWrap:"wrap",color:"fg.muted",fontSize:"xs"},
  ".search-result-group":{display:"grid",gap:"2.5"},
  ".search-result-list":{display:"grid"},
  ".search-result-row":{display:"grid",gridTemplateColumns:{base:"1fr",sm:"minmax(0,1fr) auto"},gap:"2",alignItems:"center",py:"2.5",borderTop:"1px solid",borderColor:"surface.border",_first:{borderTop:"0"},"& strong":{display:"block",fontSize:"xs"},"& span":{display:"block",mt:"1",color:"fg.muted",fontSize:"[10px]"},_hover:{"& strong":{color:"brand.hover"}}},

  ".survey-status-expired":{background:"rgba(228,121,114,.10)",color:"status.danger"},
  ".survey-deadline-warning":{display:"flex",flexDirection:{base:"column",sm:"row"},justifyContent:"space-between",alignItems:{sm:"center"},gap:"3",p:"3",border:"1px solid",borderColor:"rgba(228,191,112,.22)",borderRadius:"l2",background:"rgba(228,191,112,.05)"},
  ".survey-share-inactive":{display:"grid",gap:"1",p:"3",border:"1px solid",borderColor:"surface.border",borderRadius:"l2",background:"surface.raised","& strong":{fontSize:"xs"},"& span":{color:"fg.muted",fontSize:"[10px]",lineHeight:"1.45"}},
  ".survey-detail-grid":{display:"grid",gridTemplateColumns:{base:"1fr",xl:"minmax(0,1.5fr) minmax(280px,.7fr)"},gap:"3",alignItems:"start"},
  ".survey-control-list":{display:"grid",gap:"2"},
  ".survey-control-actions":{display:"flex",gap:"1.5",flexWrap:"wrap"},
  ".survey-participant-list,.survey-result-stack":{display:"grid",gap:"2"},
  ".survey-participant-card,.survey-result-card":{display:"grid",gap:"2.5",p:"3",border:"1px solid",borderColor:"surface.border",borderRadius:"l2",background:"surface.raised"},
  ".survey-participant-head,.survey-result-title":{display:"flex",justifyContent:"space-between",gap:"3",alignItems:"start"},
  ".survey-participant-fields,.survey-participant-answers":{display:"grid",gridTemplateColumns:{base:"1fr",sm:"repeat(2,minmax(0,1fr))"},gap:"2"},
  ".survey-text-results":{display:"grid",gap:"1.5"},
  ".survey-choice-results":{display:"grid",gap:"2"},
  ".survey-choice-result":{display:"grid",gap:"1"},
  ".survey-result-track":{height:"2",overflow:"hidden",borderRadius:"pill",background:"surface.hover","& i":{display:"block",height:"full",background:"brand.solid",borderRadius:"pill"}},

  ".public-survey-page":{minHeight:"100dvh",display:"grid",placeItems:"center",p:{base:"0",md:"5"},background:"bg"},
  ".public-survey-card":{width:"full",maxWidth:"760px",overflow:"hidden",border:{md:"1px solid"},borderColor:"surface.border",borderRadius:{md:"l4"},background:"surface.bg",boxShadow:{md:"lg"}},
  ".public-survey-header":{display:"flex",alignItems:"center",justifyContent:"space-between",gap:"3",p:{base:"4",md:"5"},borderBottom:"1px solid",borderColor:"surface.border",background:"linear-gradient(135deg,rgba(196,51,30,.12),rgba(255,255,255,.01))"},
  ".public-survey-brand":{display:"flex",alignItems:"center",gap:"3","& strong,& span":{display:"block"},"& strong":{fontSize:"sm",fontWeight:"950"},"& span":{mt:"0.5",color:"fg.muted",fontSize:"[10px]"}},
  ".public-survey-intro":{p:{base:"4",md:"5"},"& h1":{mt:"1.5",fontSize:{base:"26px",md:"34px"},fontWeight:"950",letterSpacing:"-0.04em"},"& p":{mt:"2",color:"fg.muted",fontSize:"sm",lineHeight:"1.6"}},
  ".public-survey-form":{display:"grid",gap:"3",p:{base:"4",md:"5"},pt:"0"},
  ".public-survey-question,.public-survey-identity-section":{display:"grid",gap:"2",p:"3",border:"1px solid",borderColor:"surface.border",borderRadius:"l2",background:"surface.raised"},
  ".public-identity-fields":{display:"grid",gridTemplateColumns:{base:"1fr",sm:"repeat(2,minmax(0,1fr))"},gap:"2.5"},
  ".public-survey-options":{display:"grid",gap:"1.5"},
  ".public-survey-privacy":{p:"2.5",border:"1px solid",borderColor:"brand.border",borderRadius:"l1",background:"brand.subtle",color:"fg.muted",fontSize:"[10px]",lineHeight:"1.45"},
  ".public-survey-submit":{width:{base:"full",sm:"auto"},justifySelf:{sm:"end"}},
  ".public-survey-thanks,.public-survey-closed":{display:"grid",placeItems:"center",gap:"3",p:"7",textAlign:"center","& h1,& h2":{fontSize:"xl",fontWeight:"950"},"& p":{color:"fg.muted",fontSize:"sm",lineHeight:"1.55"}},
  ".public-survey-check":{display:"grid",placeItems:"center",width:"12",height:"12",borderRadius:"pill",background:"rgba(143,198,162,.10)",color:"status.success",fontSize:"xl",fontWeight:"950"},
  ".public-survey-results":{display:"grid",gap:"2",width:"full",maxWidth:"560px"},
  ".public-result-row":{display:"flex",justifyContent:"space-between",gap:"3",p:"2.5",border:"1px solid",borderColor:"surface.border",borderRadius:"l1",background:"surface.raised"},

  ".chronicle-timeline":{display:"grid",gap:"0"},
  ".chronicle-entry":{display:"grid",gridTemplateColumns:{base:"72px 18px minmax(0,1fr)",md:"110px 24px minmax(0,1fr)"},gap:"2",alignItems:"start",minHeight:"78px"},
  ".chronicle-date":{color:"fg.muted",fontSize:"[10px]",textAlign:"right",pt:"1"},
  ".chronicle-dot":{position:"relative",display:"grid",justifyItems:"center","&::before":{content:'""',position:"absolute",top:"10px",bottom:"-12px",width:"1px",background:"surface.border"},"&::after":{content:'""',zIndex:"1",width:"2.5",height:"2.5",mt:"1",borderRadius:"pill",background:"brand.solid"}},
  ".chronicle-entry:last-child .chronicle-dot::before":{display:"none"},
  ".chronicle-content":{pb:"4","& h3":{fontSize:"sm",fontWeight:"900"},"& p":{mt:"1",color:"fg.muted",fontSize:"xs",lineHeight:"1.5"}},

  ".achievement-list":{display:"grid",gap:"2"},
  ".achievement-card":{display:"grid",gridTemplateColumns:{base:"1fr",sm:"100px minmax(0,1fr)"},gap:"3",p:"3",border:"1px solid",borderColor:"surface.border",borderRadius:"l2",background:"surface.raised"},
  ".achievement-date":{color:"brand.hover",fontSize:"xs",fontWeight:"900"},
  ".achievement-body":{"& strong":{fontSize:"sm",fontWeight:"900"},"& p":{mt:"1",color:"fg.muted",fontSize:"xs"}},
  ".achievement-links":{display:"flex",gap:"1.5",flexWrap:"wrap",mt:"2"},

  ".gallery-album-grid,.hall-grid,.hall-feature-grid,.hall-record-grid":{display:"grid",gridTemplateColumns:{base:"1fr",sm:"repeat(2,minmax(0,1fr))",xl:"repeat(3,minmax(0,1fr))"},gap:"3"},
  ".gallery-album-card,.hall-card,.hall-feature-card,.hall-record-card":{overflow:"hidden",border:"1px solid",borderColor:"surface.border",borderRadius:"l3",background:"surface.bg",_hover:{borderColor:"brand.border",background:"surface.raised"}},
  ".gallery-album-cover,.hall-hero-photo":{aspectRatio:"16/10",overflow:"hidden",background:"surface.raised","& img":{width:"full",height:"full",objectFit:"cover"}},
  ".gallery-album-empty":{display:"grid",placeItems:"center",aspectRatio:"16/10",color:"fg.muted",fontSize:"xs"},
  ".gallery-album-copy,.hall-body":{p:"3","& strong":{display:"block",fontSize:"sm",fontWeight:"900"},"& span,& p":{display:"block",mt:"1",color:"fg.muted",fontSize:"[10px]",lineHeight:"1.45"}},
  ".chronicle-gallery-create,.chronicle-gallery-manage":{display:"grid",gap:"3"},
  ".gallery-album-count":{display:"inline-flex",px:"2.5",py:"1.5",borderRadius:"pill",background:"surface.hover",color:"fg.muted",fontSize:"[10px]",fontWeight:"850"},
  ".gallery-linked-honors":{display:"flex",gap:"1.5",flexWrap:"wrap"},
  ".gallery-view-panel":{overflow:"hidden"},
  ".gallery-admin-list":{display:"grid",gap:"1.5"},

  ".hall-feature-card,.hall-record-card":{p:"3.5"},
  ".hall-card-link":{display:"block"},
  ".hall-year":{color:"brand.hover",fontSize:"[10px]",fontWeight:"900",letterSpacing:"0.08em"},
  ".hall-meta,.hall-performance-chips,.hall-places":{display:"flex",gap:"1.5",flexWrap:"wrap",mt:"2"},
  ".hall-meta span,.hall-performance-chips span,.hall-places span":{px:"2",py:"1",borderRadius:"pill",background:"surface.hover",color:"fg.muted",fontSize:"[9px]"},
  ".hall-detail-grid":{display:"grid",gridTemplateColumns:{base:"1fr",xl:"minmax(0,1.4fr) minmax(280px,.7fr)"},gap:"3"},
  ".hall-detail-stats":{display:"grid",gridTemplateColumns:{base:"repeat(2,minmax(0,1fr))",md:"repeat(4,minmax(0,1fr))"},gap:"2"},
  ".hall-detail-stats>div":{p:"2.5",border:"1px solid",borderColor:"surface.border",borderRadius:"l1",background:"surface.raised","& span,& strong":{display:"block"},"& span":{color:"fg.muted",fontSize:"[9px]"},"& strong":{mt:"1",fontSize:"lg",fontWeight:"950"}},
  ".hall-podium":{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:"2",alignItems:"end"},
  ".hall-podium>div":{display:"grid",placeItems:"center",minHeight:"86px",p:"2.5",border:"1px solid",borderColor:"surface.border",borderRadius:"l2",background:"surface.raised",textAlign:"center"},
  ".hall-podium>.first":{minHeight:"112px",borderColor:"brand.border",background:"brand.subtle"},
  ".hall-detail-notes":{p:"3",borderLeft:"3px solid",borderColor:"brand.solid",background:"brand.subtle",color:"fg.muted",fontSize:"xs",lineHeight:"1.55"},
  ".hall-album-link":{display:"inline-flex",mt:"2",color:"brand.hover",fontSize:"xs",fontWeight:"850"},
  ".destructive-inline":{display:"flex",gap:"2",flexWrap:"wrap"},
} as const;
