export const vdcSportGlobalCss = {
  ".meeting-hero": {
    display:"flex",flexDirection:{base:"column",md:"row"},alignItems:{md:"center"},justifyContent:"space-between",
    gap:"4",p:{base:"3.5",md:"4"},border:"1px solid",borderColor:"surface.border",borderRadius:"l4",
    background:"linear-gradient(135deg,rgba(196,51,30,.09),rgba(255,255,255,.01))",boxShadow:"sm",
  },
  ".meeting-hero-side":{display:"flex",alignItems:"center",gap:"2",flexWrap:"wrap",justifyContent:{md:"flex-end"}},
  ".meeting-summary-grid":{display:"grid",gridTemplateColumns:{base:"repeat(2,minmax(0,1fr))",lg:"repeat(4,minmax(0,1fr))"},gap:"2"},
  ".meeting-summary-grid>article,.meeting-summary-grid>div": {
    p:"3",border:"1px solid",borderColor:"surface.border",borderRadius:"l2",background:"surface.bg",
    "& span,& strong,& small":{display:"block"},"& span":{color:"fg.muted",fontSize:"[9px]"},"& strong":{mt:"1",fontSize:"lg",fontWeight:"950"},"& small":{mt:"1",color:"fg.subtle",fontSize:"[9px]"},
  },
  ".sync-chip":{display:"inline-flex",alignItems:"center",gap:"1.5",px:"2.5",py:"1.5",border:"1px solid",borderColor:"brand.border",borderRadius:"pill",background:"brand.subtle",color:"brand.hover",fontSize:"[10px]",fontWeight:"850"},
  ".training-status-planned":{background:"rgba(228,191,112,.10) !important",color:"status.warning !important"},
  ".training-status-completed":{background:"rgba(143,198,162,.10) !important",color:"status.success !important"},
  ".training-status-cancelled":{background:"rgba(228,121,114,.10) !important",color:"status.danger !important"},
  ".training-activity-row-rich":{borderRadius:"l1",px:"2",_hover:{background:"surface.raised"}},
  ".event-club":{background:"#c4331e"},
  ".event-league":{background:"#e4bf70"},
  ".event-training":{background:"#8fc6a2"},
  ".event-tournament":{background:"#86bce8"},
  ".event-board":{background:"#a98fd6"},
  ".team-management-list,.team-source-stack,.training-upcoming-list,.training-history-list,.training-pause-list,.training-season-list":{display:"grid",gap:"2"},
  ".team-overview-card": {
    display:"grid",gap:"3",p:"3.5",border:"1px solid",borderColor:"surface.border",borderRadius:"l3",background:"surface.bg",
    transitionDuration:"normal",transitionProperty:"background, border-color, transform",
    _hover:{borderColor:"brand.border",background:"surface.raised",transform:"translateY(-1px)"},
  },
  ".team-overview-head":{display:"flex",justifyContent:"space-between",alignItems:"start",gap:"3","& h2":{fontSize:"sm",fontWeight:"900"}},
  ".team-badge":{display:"grid",placeItems:"center",width:"11",height:"11",border:"1px solid",borderColor:"brand.border",borderRadius:"pill",background:"brand.subtle",color:"brand.hover",fontSize:"xs",fontWeight:"950"},
  ".team-overview-grid,.team-detail-grid":{display:"grid",gridTemplateColumns:{base:"1fr",lg:"repeat(2,minmax(0,1fr))"},gap:"3"},
  ".team-next-match":{p:"3",borderLeft:"3px solid",borderColor:"brand.solid",borderRadius:"0 l2 l2 0",background:"brand.subtle"},
  ".team-detail-main,.team-detail-side":{display:"grid",gap:"3"},
  ".roster-row":{display:"grid",gridTemplateColumns:{base:"40px minmax(0,1fr)",md:"40px minmax(0,1fr) auto"},gap:"2.5",alignItems:"center",py:"2.5",borderTop:"1px solid",borderColor:"surface.border"},
  ".roster-row:first-child":{borderTop:"0"},
  ".roster-role":{color:"fg.muted",fontSize:"[10px]"},
  ".roster-actions":{gridColumn:{base:"2",md:"auto"},display:"flex",gap:"1.5",flexWrap:"wrap"},

  ".training-heading":{display:"flex",flexDirection:{base:"column",md:"row"},alignItems:{md:"end"},justifyContent:"space-between",gap:"3"},
  ".training-heading-actions":{display:"flex",gap:"2",flexWrap:"wrap"},
  ".training-weekday-grid":{display:"grid",gridTemplateColumns:{base:"1fr",md:"repeat(2,minmax(0,1fr))"},gap:"3"},
  ".training-weekday-card":{display:"grid",gap:"2.5",p:"3.5",border:"1px solid",borderColor:"surface.border",borderRadius:"l3",background:"surface.bg"},
  ".training-rule-chip":{display:"inline-flex",width:"fit-content",px:"2.5",py:"1.5",borderRadius:"pill",background:"brand.subtle",color:"brand.hover",fontSize:"[10px]",fontWeight:"850"},
  ".training-upcoming-row,.training-history-row,.training-season-row":{display:"grid",gridTemplateColumns:{base:"1fr",sm:"auto minmax(0,1fr) auto"},gap:"2.5",alignItems:"center",p:"2.5",border:"1px solid",borderColor:"surface.border",borderRadius:"l2",background:"surface.raised"},
  ".training-date-badge":{display:"grid",placeItems:"center",width:"12",height:"12",borderRadius:"l2",background:"brand.subtle",color:"brand.hover",fontSize:"xs",fontWeight:"900"},
  ".training-month-grid":{display:"grid",gridTemplateColumns:{base:"repeat(2,minmax(0,1fr))",md:"repeat(3,minmax(0,1fr))",xl:"repeat(6,minmax(0,1fr))"},gap:"2"},
  ".training-month-card":{p:"2.5",border:"1px solid",borderColor:"surface.border",borderRadius:"l2",background:"surface.raised"},
  ".training-activity-head":{display:"flex",justifyContent:"space-between",gap:"3",alignItems:"center"},
  ".training-filter-bar":{display:"flex",gap:"2",flexWrap:"wrap","& select,& input":{minHeight:"9",px:"2.5",border:"1px solid",borderColor:"surface.border",borderRadius:"l1",background:"surface.bg",color:"fg"}},
  ".training-activity-note,.training-info-box,.training-report-note,.training-season-note":{p:"3",border:"1px solid",borderColor:"brand.border",borderRadius:"l2",background:"brand.subtle",color:"fg.muted",fontSize:"xs",lineHeight:"1.5"},
  ".training-activity-list":{display:"grid"},
  ".training-activity-row":{display:"grid",gridTemplateColumns:{base:"36px minmax(0,1fr)",md:"36px minmax(0,1fr) auto"},gap:"2.5",alignItems:"center",py:"2.5",borderTop:"1px solid",borderColor:"surface.border"},
  ".training-activity-row:first-child":{borderTop:"0"},
  ".training-rank":{display:"grid",placeItems:"center",width:"8",height:"8",borderRadius:"pill",background:"surface.hover",color:"brand.hover",fontSize:"[10px]",fontWeight:"900"},
  ".training-member":{minWidth:"0","& strong,& span":{display:"block"},"& strong":{fontSize:"xs"},"& span":{mt:"1",color:"fg.muted",fontSize:"[10px]"}},
  ".training-rate":{color:"brand.hover",fontSize:"sm",fontWeight:"900"},
  ".training-management-grid":{display:"grid",gridTemplateColumns:{base:"1fr",xl:"repeat(2,minmax(0,1fr))"},gap:"3"},
  ".training-session-meta":{display:"flex",gap:"1.5",flexWrap:"wrap","& span":{px:"2",py:"1",borderRadius:"pill",background:"surface.hover",color:"fg.muted",fontSize:"[9px]"}},

  ".training-report-page":{display:"grid",gap:{base:"4",md:"5"}},
  ".training-report-heading":{display:"flex",flexDirection:{base:"column",md:"row"},justifyContent:"space-between",gap:"3",alignItems:{md:"end"}},
  ".training-report-actions":{display:"flex",gap:"2",flexWrap:"wrap"},
  ".training-report-switcher":{display:"grid",gridTemplateColumns:{base:"1fr 1fr",md:"repeat(4,minmax(0,1fr))"},gap:"1",p:"1",border:"1px solid",borderColor:"surface.border",borderRadius:"l2",background:"surface.bg"},
  ".training-report-switcher a":{display:"grid",placeItems:"center",minHeight:"9",px:"2",borderRadius:"l1",color:"fg.muted",fontSize:"xs",fontWeight:"800",_hover:{background:"surface.hover",color:"fg"}},
  ".training-report-switcher a.active":{background:"brand.subtle",color:"brand.hover"},
  ".training-report-meta":{display:"flex",gap:"1.5",flexWrap:"wrap"},
  ".training-report-split":{display:"grid",gridTemplateColumns:{base:"1fr",xl:"repeat(2,minmax(0,1fr))"},gap:"3"},
  ".training-report-weekdays,.training-report-seasons,.training-team-comparison,.training-report-months":{display:"grid",gap:"2"},
  ".training-team-card,.training-report-month":{display:"grid",gap:"2",p:"3",border:"1px solid",borderColor:"surface.border",borderRadius:"l2",background:"surface.raised"},
  ".training-team-head":{display:"flex",justifyContent:"space-between",gap:"3"},
  ".training-team-metrics":{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:"2"},
  ".training-team-rate":{fontSize:"lg",fontWeight:"950",color:"brand.hover"},
  ".training-report-month-track,.coverage-track":{height:"2",overflow:"hidden",borderRadius:"pill",background:"surface.hover","& i,& span":{display:"block",height:"full",borderRadius:"pill",background:"brand.solid"}},
  ".training-team-month-table,.training-report-member-table":{display:"grid",overflowX:"auto"},
  ".training-team-month-head,.training-team-month-row,.training-report-member-head,.training-report-member-row":{display:"grid",gridTemplateColumns:"minmax(180px,1fr) repeat(3,minmax(90px,.4fr))",gap:"2",minWidth:"600px",p:"2.5",borderTop:"1px solid",borderColor:"surface.border"},
  ".training-team-month-head,.training-report-member-head":{borderTop:"0",background:"surface.raised",color:"fg.muted",fontSize:"[9px]",fontWeight:"850",textTransform:"uppercase"},
  ".training-season-management":{display:"grid",gap:"3"},
  ".training-season-actions":{display:"flex",gap:"1.5",flexWrap:"wrap"},
  ".training-season-new":{display:"grid",gap:"2.5"},
  ".training-report-footer":{color:"fg.subtle",fontSize:"[10px]",textAlign:"center"},

  ".calendar-sync-panel":{borderColor:"brand.border !important"},
  ".calendar-sync-head":{display:"flex",flexDirection:{base:"column",md:"row"},justifyContent:"space-between",gap:"3",alignItems:{md:"center"}},
  ".calendar-sync-grid":{display:"grid",gridTemplateColumns:{base:"1fr",md:"repeat(2,minmax(0,1fr))"},gap:"2",mt:"3"},
  ".calendar-sync-card":{display:"grid",gap:"2",p:"3",border:"1px solid",borderColor:"surface.border",borderRadius:"l2",background:"surface.raised"},
  ".calendar-list":{display:"grid",gap:"2"},
  ".calendar-event":{display:"grid",gridTemplateColumns:{base:"8px minmax(0,1fr)",md:"8px minmax(0,1fr) auto"},gap:"2.5",alignItems:"center",p:"3",border:"1px solid",borderColor:"surface.border",borderRadius:"l2",background:"surface.bg"},
  ".event-type-dot":{width:"2",height:"10",borderRadius:"pill",background:"brand.solid"},
  ".calendar-event-main":{minWidth:"0"},
  ".calendar-event-title":{display:"flex",alignItems:"center",gap:"2",flexWrap:"wrap","& strong":{fontSize:"xs",fontWeight:"900"}},
  ".calendar-event-main span":{display:"block",mt:"1",color:"fg.muted",fontSize:"[10px]"},
  ".calendar-event-actions":{gridColumn:{base:"2",md:"auto"},display:"flex",gap:"1.5",flexWrap:"wrap"},

  ".team-stat-list,.coverage-list,.compact-activity-list":{display:"grid"},
  ".team-stat-row,.coverage-row,.compact-activity-list>div":{py:"2.5",borderTop:"1px solid",borderColor:"surface.border","&:first-child":{borderTop:"0"}},
  ".coverage-head":{display:"flex",justifyContent:"space-between",gap:"2","& b":{color:"brand.hover"}},
  ".activity-bars":{display:"grid",gap:"2"},
  ".activity-bar-row":{display:"grid",gridTemplateColumns:"minmax(120px,.7fr) minmax(0,1fr) 50px",gap:"2",alignItems:"center","&>div":{height:"2",overflow:"hidden",borderRadius:"pill",background:"surface.hover"},"& i":{display:"block",height:"full",background:"brand.solid"}},
  ".statistics-footnote":{color:"fg.subtle",fontSize:"[10px]",lineHeight:"1.5"},
  ".training-stat-grid":{display:"grid",gridTemplateColumns:{base:"repeat(2,minmax(0,1fr))",lg:"repeat(4,minmax(0,1fr))"},gap:"2"},
} as const;
