export const vdcMinutesGlobalCss = {
  ".minutes-page,.secretary-workspace-page,.meeting-correction-page": {
    display: "grid",
    gap: { base: "4", md: "5" },
  },

  ".secretary-workspace,.meeting-correction-hero": {
    display: "grid",
    gap: "3",
    p: { base: "3.5", md: "4" },
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: "l4",
    background: "linear-gradient(135deg,rgba(196,51,30,.08),rgba(255,255,255,.01))",
    boxShadow: "sm",
  },
  ".secretary-workspace-head": {
    display: "flex",
    flexDirection: { base: "column", md: "row" },
    alignItems: { md: "center" },
    justifyContent: "space-between",
    gap: "3",
    "& h1": { mt: "1", fontSize: { base: "26px", md: "34px" }, fontWeight: "950", letterSpacing: "-0.04em" },
    "& p": { mt: "1.5", color: "fg.muted", fontSize: "xs" },
  },
  ".secretary-workspace-actions,.minutes-review-actions,.minutes-archive-actions,.minutes-toolbar": {
    display: "flex",
    gap: "2",
    flexWrap: "wrap",
    alignItems: "center",
  },

  ".minutes-workflow": {
    display: "grid",
    gridTemplateColumns: { base: "1fr", md: "repeat(3,minmax(0,1fr))" },
    gap: "1",
    p: "1",
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: "l2",
    background: "surface.bg",
  },
  ".minutes-workflow>div,.minutes-workflow>a": {
    display: "grid",
    gap: "0.5",
    p: "2.5",
    borderRadius: "l1",
    color: "fg.muted",
    "& strong": { color: "fg", fontSize: "xs", fontWeight: "900" },
    "& small": { fontSize: "[9px]" },
  },
  ".minutes-workflow>.is-current,.minutes-workflow>a.is-current": {
    background: "brand.subtle",
    color: "brand.hover",
  },

  ".secretary-meta-grid,.minutes-quality-strip,.minutes-formality-grid,.minutes-attendance-grid,.meeting-correction-guide-grid": {
    display: "grid",
    gridTemplateColumns: { base: "repeat(2,minmax(0,1fr))", lg: "repeat(4,minmax(0,1fr))" },
    gap: "2",
  },
  ".secretary-meta-grid>div,.minutes-quality-strip>div,.minutes-formality-grid>div,.minutes-attendance-grid>div,.meeting-correction-guide-grid>a,.meeting-correction-guide-grid>div": {
    p: "2.5",
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: "l1",
    background: "surface.raised",
    "& span,& strong,& small": { display: "block" },
    "& span": { color: "fg.muted", fontSize: "[9px]", textTransform: "uppercase", letterSpacing: "0.05em" },
    "& strong": { mt: "1", fontSize: "xs", fontWeight: "900" },
    "& small": { mt: "1", color: "fg.muted", fontSize: "[9px]", lineHeight: "1.4" },
  },

  ".minutes-readiness": {
    display: "grid",
    gap: "2",
    p: "3",
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: "l3",
    background: "surface.bg",
  },
  ".minutes-readiness.is-ready": {
    borderColor: "rgba(143,198,162,.22)",
    background: "rgba(143,198,162,.04)",
  },
  ".minutes-correction-entry,.minutes-return-note,.minutes-waiting": {
    p: "3",
    border: "1px solid",
    borderColor: "rgba(228,191,112,.22)",
    borderRadius: "l2",
    background: "rgba(228,191,112,.05)",
    color: "fg.muted",
    fontSize: "xs",
    lineHeight: "1.5",
  },

  ".secretary-approval-panel,.minutes-review-panel,.minutes-history-panel,.minutes-archive-complete": {
    overflow: "hidden",
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: "l3",
    background: "surface.bg",
  },
  ".minutes-review-head": {
    display: "flex",
    flexDirection: { base: "column", sm: "row" },
    justifyContent: "space-between",
    gap: "3",
    alignItems: { sm: "center" },
    p: "3.5",
    borderBottom: "1px solid",
    borderColor: "surface.border",
    "& h2": { mt: "1", fontSize: "lg", fontWeight: "900" },
  },
  ".minutes-review-checklist": {
    display: "grid",
    gridTemplateColumns: { base: "1fr", sm: "repeat(2,minmax(0,1fr))", xl: "repeat(5,minmax(0,1fr))" },
    gap: "2",
    p: "3.5",
  },
  ".minutes-review-checklist>div": {
    p: "2.5",
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: "l1",
    background: "surface.raised",
    "& span,& strong": { display: "block" },
    "& span": { color: "fg.muted", fontSize: "[9px]" },
    "& strong": { mt: "1", fontSize: "xs" },
  },
  ".minutes-review-preview,.minutes-review-decision": {
    p: "3.5",
    borderTop: "1px solid",
    borderColor: "surface.border",
  },
  ".minutes-review-primary": { display: "flex", justifyContent: "flex-end", mt: "3" },
  ".minutes-return-drawer": {
    mt: "3",
    overflow: "hidden",
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: "l2",
    "&>summary": { p: "2.5", cursor: "pointer", listStyle: "none", color: "fg.muted", fontSize: "xs", fontWeight: "800" },
    "&>summary::-webkit-details-marker": { display: "none" },
    "&[open]>summary": { borderBottom: "1px solid", borderColor: "surface.border", color: "fg" },
    "&>form": { p: "2.5" },
  },
  ".minutes-archive-complete": {
    display: "flex",
    flexDirection: { base: "column", md: "row" },
    justifyContent: "space-between",
    alignItems: { md: "center" },
    gap: "3",
    p: "3.5",
    borderColor: "rgba(143,198,162,.22)",
    background: "rgba(143,198,162,.035)",
  },

  ".minutes-history-content": { p: "3.5" },
  ".minutes-history-list": { display: "grid", gap: "1.5" },
  ".minutes-history-list>div": {
    display: "flex",
    flexDirection: { base: "column", sm: "row" },
    justifyContent: "space-between",
    gap: "2",
    p: "2",
    borderTop: "1px solid",
    borderColor: "surface.border",
  },

  ".minutes-preview-drawer": {
    overflow: "hidden",
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: "l3",
    background: "surface.bg",
    "&>summary": { p: "3", cursor: "pointer", listStyle: "none", fontSize: "xs", fontWeight: "850" },
    "&>summary::-webkit-details-marker": { display: "none" },
    "&[open]>summary": { borderBottom: "1px solid", borderColor: "surface.border" },
  },

  ".minutes-document": {
    position: "relative",
    display: "grid",
    gap: "4",
    maxWidth: "900px",
    mx: "auto",
    p: { base: "4", md: "7" },
    background: "warmWhite",
    color: "ink",
    borderRadius: "l2",
    boxShadow: "md",
    "& .eyebrow": { color: "vdcRed" },
  },
  ".minutes-draft-watermark": {
    position: "absolute",
    right: "4",
    top: "4",
    color: "rgba(196,51,30,.28)",
    fontSize: "xl",
    fontWeight: "950",
    transform: "rotate(8deg)",
  },
  ".minutes-header": {
    display: "flex",
    flexDirection: { base: "column", sm: "row" },
    justifyContent: "space-between",
    gap: "4",
    pb: "4",
    borderBottom: "2px solid #c4331e",
    "& h1": { mt: "1", fontSize: "2xl", fontWeight: "950" },
  },
  ".minutes-brand": {
    display: "flex",
    alignItems: "center",
    gap: "3",
    "& img": { width: "48px", height: "48px" },
  },
  ".minutes-officer-meta": {
    display: "grid",
    gap: "1",
    fontSize: "xs",
  },
  ".minutes-formalities,.minutes-agenda,.minutes-signatures,.minutes-attachments": {
    display: "grid",
    gap: "3",
  },
  ".minutes-guest-list": { display: "grid", gap: "1" },
  ".minutes-top": {
    display: "grid",
    gap: "2",
    py: "3",
    borderTop: "1px solid rgba(14,14,16,.18)",
  },
  ".minutes-top:first-child": { borderTop: "0" },
  ".minutes-top-title": {
    display: "flex",
    alignItems: "start",
    justifyContent: "space-between",
    gap: "3",
    "& h3": { fontSize: "sm", fontWeight: "900" },
  },
  ".minutes-agenda-type,.minutes-spontaneous,.minutes-exclusions,.minutes-task": {
    width: "fit-content",
    px: "2",
    py: "1",
    borderRadius: "pill",
    background: "rgba(14,14,16,.07)",
    fontSize: "[10px]",
  },
  ".minutes-resolution": {
    display: "grid",
    gap: "2",
    p: "3",
    borderLeft: "3px solid #c4331e",
    background: "rgba(196,51,30,.055)",
  },
  ".minutes-resolution-head": {
    display: "flex",
    justifyContent: "space-between",
    gap: "3",
  },
  ".minutes-vote": {
    display: "flex",
    gap: "2",
    flexWrap: "wrap",
    fontSize: "xs",
  },

  ".meeting-correction-page": { display: "grid", gap: { base: "4", md: "5" } },
  ".meeting-correction-guide-head": {
    display: "flex",
    flexDirection: { base: "column", sm: "row" },
    justifyContent: "space-between",
    gap: "3",
    alignItems: { sm: "center" },
  },
  ".meeting-correction-grid": {
    display: "grid",
    gridTemplateColumns: { base: "1fr", xl: "repeat(2,minmax(0,1fr))" },
    gap: "3",
  },
  ".meeting-correction-group": {
    overflow: "hidden",
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: "l3",
    background: "surface.bg",
  },
  ".meeting-correction-group-summary": {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "3",
    p: "3.5",
    cursor: "pointer",
    listStyle: "none",
  },
  ".meeting-correction-group-summary::-webkit-details-marker": { display: "none" },
  ".meeting-correction-group[open]>.meeting-correction-group-summary": {
    borderBottom: "1px solid",
    borderColor: "surface.border",
    background: "surface.raised",
  },
  ".meeting-correction-group-body": { display: "grid", gap: "3", p: "3.5" },
  ".meeting-correction-section,.meeting-correction-agenda,.meeting-correction-attachments,.meeting-correction-exclusions": {
    display: "grid",
    gap: "2.5",
    p: "3",
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: "l2",
    background: "surface.raised",
  },
  ".meeting-correction-agenda-body": { display: "grid", gap: "2.5" },
  ".meeting-correction-form,.meeting-correction-add-form,.resolution-correction-form,.meeting-general-attachment-upload": {
    display: "grid",
    gap: "2.5",
  },
  ".meeting-correction-form label,.meeting-correction-add-form label,.resolution-correction-form label": {
    display: "grid",
    gap: "1.5",
    color: "fg.muted",
    fontSize: "xs",
    fontWeight: "750",
  },
  ".meeting-correction-form input,.meeting-correction-form select,.meeting-correction-form textarea,.meeting-correction-add-form input,.meeting-correction-add-form select,.meeting-correction-add-form textarea,.resolution-correction-form input,.resolution-correction-form select,.resolution-correction-form textarea": {
    width: "full",
    minHeight: "10",
    p: "2.5",
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: "l1",
    background: "surface.bg",
    color: "fg",
    outline: "none",
    _focus: { borderColor: "brand.solid", boxShadow: "focus" },
  },
  ".correction-reason": {
    p: "2.5",
    border: "1px solid",
    borderColor: "rgba(228,191,112,.20)",
    borderRadius: "l1",
    background: "rgba(228,191,112,.04)",
  },
  ".meeting-correction-list,.meeting-correction-remove-list,.meeting-change-list": {
    display: "grid",
    gap: "1.5",
  },
  ".meeting-correction-list>div,.meeting-correction-remove-list>div,.meeting-change-list>div": {
    p: "2.5",
    border: "1px solid",
    borderColor: "surface.border",
    borderRadius: "l1",
    background: "surface.bg",
  },
  ".correction-state": {
    display: "inline-flex",
    width: "fit-content",
    px: "2",
    py: "1",
    borderRadius: "pill",
    fontSize: "[10px]",
    fontWeight: "850",
  },
  ".correction-state.is-neutral": { background: "surface.hover", color: "fg.muted" },
  ".meeting-change-history": {
    display: "grid",
    gap: "2",
  },

  "@media print": {
    ".no-print": { display: "none !important" },
    ".minutes-page": { background: "white" },
    ".minutes-document": {
      boxShadow: "none",
      maxWidth: "none",
      borderRadius: "0",
    },
  },
} as const;
