export const vdcClubGlobalCss = {
  ".club-profile-grid": {
    display:"grid",gridTemplateColumns:{base:"1fr",xl:"minmax(0,1.55fr) minmax(300px,.75fr)"},gap:"3",alignItems:"start",
  },
  ".club-profile-side":{display:"grid",gap:"3"},
  ".club-profile-subhead":{mt:"2",pt:"3",borderTop:"1px solid",borderColor:"surface.border"},
  ".club-movement-grid":{display:"grid",gridTemplateColumns:{base:"repeat(2,minmax(0,1fr))",md:"repeat(3,minmax(0,1fr))"},gap:"2"},
  ".club-movement-grid>div,.member-lifecycle-summary>article": {
    p:"3",border:"1px solid",borderColor:"surface.border",borderRadius:"l2",background:"surface.raised",
    "& span,& strong":{display:"block"},"& span":{color:"fg.muted",fontSize:"[9px]"},"& strong":{mt:"1",fontSize:"lg",fontWeight:"950"},
  },

  ".member-row": {
    display:"grid",gridTemplateColumns:{base:"40px minmax(0,1fr)",md:"42px minmax(0,1fr) minmax(150px,.55fr)"},gap:"3",alignItems:"center",
    py:"2.5",borderTop:"1px solid",borderColor:"surface.border",
  },
  ".member-row:first-child":{borderTop:"0"},
  ".member-row:hover .member-main strong":{color:"brand.hover"},
  ".member-avatar": {
    display:"grid",placeItems:"center",width:"10",height:"10",border:"1px solid",borderColor:"brand.border",borderRadius:"pill",
    background:"brand.subtle",color:"brand.hover",fontSize:"xs",fontWeight:"950",
  },
  ".member-main,.member-meta":{minWidth:"0"},
  ".member-main strong,.member-main span,.member-meta span":{display:"block"},
  ".member-main strong":{fontSize:"xs",fontWeight:"850"},
  ".member-main span,.member-meta span":{mt:"1",overflow:"hidden",color:"fg.muted",fontSize:"[10px]",textOverflow:"ellipsis",whiteSpace:"nowrap"},
  ".member-meta":{gridColumn:{base:"2",md:"auto"},textAlign:{base:"left",md:"right"}},
  ".member-notice":{display:"block",mt:"1",color:"status.warning",fontSize:"[10px]",fontWeight:"800"},
  ".member-history-list,.member-training-history,.member-fee-list":{display:"grid"},
  ".member-history-row,.member-fee-row": {
    display:"grid",gridTemplateColumns:{base:"1fr",sm:"minmax(0,1fr) auto"},gap:"2",alignItems:"center",py:"2.5",
    borderTop:"1px solid",borderColor:"surface.border",
  },
  ".member-history-row:first-child,.member-fee-row:first-child":{borderTop:"0"},
  ".member-history-row strong,.member-history-row span,.member-fee-row strong,.member-fee-row span":{display:"block"},
  ".member-history-row span,.member-fee-row span":{mt:"1",color:"fg.muted",fontSize:"[10px]"},
  ".member-lifecycle-summary":{display:"grid",gridTemplateColumns:{base:"repeat(2,minmax(0,1fr))",lg:"repeat(4,minmax(0,1fr))"},gap:"2"},
  ".membership-status-box":{p:"3",border:"1px solid",borderColor:"brand.border",borderRadius:"l2",background:"brand.subtle"},
  ".account-summary":{display:"grid",overflow:"hidden",border:"1px solid",borderColor:"surface.border",borderRadius:"l2"},
  ".account-summary>div": {
    display:"flex",flexDirection:{base:"column",sm:"row"},justifyContent:"space-between",gap:"1.5",p:"2.5",borderTop:"1px solid",borderColor:"surface.border",
    "&:first-child":{borderTop:"0"},"& span":{color:"fg.muted",fontSize:"xs"},"& strong":{fontSize:"xs",textAlign:{sm:"right"}},
  },
  ".role-chips":{display:"flex",gap:"1.5",flexWrap:"wrap",my:"3"},
  ".role-chips span,.captain-chip":{px:"2.5",py:"1.5",border:"1px solid",borderColor:"brand.border",borderRadius:"pill",background:"brand.subtle",color:"brand.hover",fontSize:"[10px]",fontWeight:"800"},
  ".role-form":{mt:"3",pt:"3",borderTop:"1px solid",borderColor:"surface.border"},
  ".checkbox-grid":{display:"grid",gridTemplateColumns:{base:"1fr",sm:"repeat(2,minmax(0,1fr))"},gap:"2"},
  ".member-training-summary":{display:"grid",gap:"2"},
  ".member-fee-row-extended":{gridTemplateColumns:{base:"1fr",md:"minmax(0,1fr) auto auto"}},
  ".member-fee-money":{textAlign:{md:"right"}},

  ".destructive-zone":{borderColor:"rgba(228,121,114,.22) !important",background:"rgba(228,121,114,.035) !important"},
  ".destructive-inline-form":{display:"flex",gap:"2",flexWrap:"wrap"},

  ".sponsor-list":{display:"grid",gridTemplateColumns:{base:"1fr",xl:"repeat(2,minmax(0,1fr))"},gap:"3"},
  ".sponsor-card":{display:"grid",gap:"3",p:"3.5",border:"1px solid",borderColor:"surface.border",borderRadius:"l3",background:"surface.bg"},
  ".sponsor-card-head":{display:"flex",justifyContent:"space-between",gap:"3",alignItems:"start","& h2":{fontSize:"sm",fontWeight:"900"}},
  ".sponsor-status":{display:"inline-flex",px:"2.5",py:"1.5",borderRadius:"pill",fontSize:"[10px]",fontWeight:"850"},
  ".sponsor-active":{background:"rgba(143,198,162,.10)",color:"status.success"},
  ".sponsor-expired":{background:"rgba(228,191,112,.10)",color:"status.warning"},
  ".sponsor-meta":{display:"flex",gap:"1.5",flexWrap:"wrap","& span":{px:"2",py:"1",borderRadius:"pill",background:"surface.hover",color:"fg.muted",fontSize:"[9px]"}},
  ".sponsor-benefits":{display:"grid",gap:"1.5","& li":{color:"fg.muted",fontSize:"xs"}},
  ".sponsor-status-form":{display:"flex",gap:"1.5",flexWrap:"wrap","& select":{minHeight:"8",px:"2",border:"1px solid",borderColor:"surface.border",borderRadius:"l1",background:"surface.bg",color:"fg"}},

  ".archive-grid":{display:"grid",gridTemplateColumns:{base:"1fr",xl:"repeat(2,minmax(0,1fr))"},gap:"3"},
  ".archive-list,.archive-mini-list":{display:"grid"},
  ".archive-list>article,.archive-mini-list>div":{py:"2.5",borderTop:"1px solid",borderColor:"surface.border","&:first-child":{borderTop:"0"}},
  ".archive-row-actions":{display:"flex",gap:"1.5",flexWrap:"wrap",mt:"2"},
  ".document-title-link":{fontWeight:"850",_hover:{color:"brand.hover"}},
} as const;
